# My deployer
name: hexo-deploy
on:
  push:
  issues:
    types: [opened, edited, closed, reopened]

jobs:
  close-issue:
    name: Close Gitalk Issues
    runs-on: ubuntu-latest

    steps:
      # Checkout Codes
      - name: Checkout Codes
        uses: actions/checkout@v2

      # Close Issues
      - name: Close Issues
        uses: bdougie/close-issues-based-on-label@v1.2
        env:
          LABEL: Gitalk
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
