# My deployer
name: hexo-deploy
on:
  push:
  issues:
    types: [opened, edited, closed, reopened]

jobs:
  close-issue:
    name: Close Gitalk Issues
    runs-on: ubuntu-latest

    steps:
      # Checkout Codes
      - name: Checkout Codes
        uses: actions/checkout@v2

      # Close Issues
      - name: Close Issues
        uses: lowply/auto-closer@v0.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          AC_LABEL: "Gitalk"
          AC_KEEP: 1
