# My deployer
name: hexo-deploy
on:
  push:
  issues:
    types: [opened, edited, closed, reopened]

jobs:
  close-issue:
    name: Close Gitalk Issues
    runs-on: ubuntu-latest

    steps:
      # Checkout Codes
      - name: Checkout Codes
        uses: actions/checkout@v2

      # Setup Cache Directory
      - name: Setup Cache Directory
        uses: actions/cache@v2
        env:
          cache-name: auto-closer
        with:
          path: ~/.auto-closer
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-

      # Close Issues
      - name: Close Issues
        uses: Van-Nya/auto-closer@main
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          AC_LABEL: "Gitalk"
          AC_KEEP: 0
